services:
  lobby_service:
    build: ./lobby_service
    ports:
      - "5000:5000"
    depends_on:
      - redis_service

  session_service:
    build: ./session_service
    ports:
      - "5001:5001"
    depends_on:
      - redis_service

  # game_engine:
  #   build: ./game_engine
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     - redis



  redis_service:
    image: "redis:alpine"
  
