services:
  lobby_service:
    build: ./lobby_service
    ports:
      - "5000:5000"
    depends_on:
      redis

  # game_engine:
  #   build: ./game_engine
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     redis

  redis:
    image: "redis:alpine"
  
